version: "3.7"
services:
  chromedriver:
    build: .
    cap_add:
      - SYS_ADMIN
    command: chromedriver --verbose
    container_name: chromedriver
    environment:
      DISPLAY: host.docker.internal:0
    ports:
      - 9515:9515
    shm_size: 1gb
    user: driver
    working_dir: /home/driver/
