version: "3.7"
services:
  chromedriver:
    build: .
    cap_add:
      - SYS_ADMIN
    container_name: chromedriver
    command: ["--whitelisted-ips", "--verbose"]
    entrypoint: ["/usr/bin/chromedriver"]
    environment:
      DISPLAY: host.docker.internal:0
    image: jmera/chromedriver:latest
    ports:
      - 9515:9515
    shm_size: 1gb
