version: "3.7"
services:
  chromium:
    container_name: chromium
    build: .
    user: chromium
    working_dir: /home/chromium/
    environment:
      DISPLAY: host.docker.internal:0
    cap_add:
      - SYS_ADMIN
    shm_size: 1gb
    command: chromium-browser
